// Offline regeneration from hash-verified extracted members, never opens an archive.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'../..'),docs=path.join(root,'docs/analysis-2320'),source=path.join(docs,'modern-reader/members-ko-2.320');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex'),assert=(v,m)=>{if(!v)throw Error(m)};
const manifest=JSON.parse(fs.readFileSync(path.join(docs,'modern-reader/confirmed-source-manifest.json'))).archives.find(a=>a.version==='2.320');
assert(manifest.currentArchiveSha256.toLowerCase()==='68445631fdaca12a343e9465e5bc5dc9b4c8c6cc927d701f52e2cb822821e15f','archive pin');
assert(manifest.members.length===8&&manifest.members.find(m=>m.name==='war3map.j').requestedLocale===1042,'eight sources / Korean JASS');
const bytes={};const members=manifest.members.map(m=>{const b=fs.readFileSync(path.join(source,m.name));assert(b.length===m.lengthBytes&&hash(b)===m.sha256.toLowerCase(),'member '+m.name);bytes[m.name]=b;return {Name:m.name,LengthBytes:b.length,Sha256:hash(b)}}).sort((a,b)=>a.Name.localeCompare(b.Name,'en'));
const ids=['e0IX','e0IA','e01A','e019','e018','e017','e016'],kinds=['RandomReward','MechanicalDummyNotReward','TranscendenceReward','RareReward','CommonSelectableReward','UncommonReward','SpecialReward'];
const b=bytes['war3map.w3u'];let p=0,total=0,mods=0,zero=0;const need=n=>assert(n>=0&&p+n<=b.length,'W3U bounds '+p),i=()=>{need(4);const n=b.readInt32LE(p);p+=4;return n},raw=()=>{need(4);const s=b.toString('latin1',p,p+4);p+=4;return s},bounded=n=>{assert(n>=0&&n<=100000,'W3U count');return n};const version=i();assert(version===3,'version');let tables=[],records=[];
for(const table of ['Original','Custom']){const co=p,count=bounded(i()),rs=p;for(let ri=0;ri<count;ri++){const start=p,base=raw(),custom=raw(),id=custom==='\0\0\0\0'?base:custom,rc=bounded(i());assert(rc===1,'reserved count');const reserved=i(),mcOffset=p,mc=bounded(i()),fields=[];total++;mods+=mc;for(let mi=0;mi<mc;mi++){const fo=p,fid=raw(),type=i(),vo=p;let value;if(type===0)value=String(i());else if(type===1||type===2){need(4);const v=b.readFloatLE(p);assert(Number.isFinite(v),'finite');value=String(v);p+=4}else if(type===3){const end=b.indexOf(0,p);assert(end>=p&&end-p<=1048576,'string bound');const bb=b.subarray(p,end);value=bb.toString('utf8');assert(Buffer.from(value).equals(bb),'UTF8');p=end+1}else throw Error('value type');need(4);const so=p,sanity=b.subarray(p,p+4).toString('hex');p+=4;if(sanity==='00000000')zero++;fields.push({ModificationIndex:mi,StartOffset:fo,FieldId:fid,ValueType:type,ValueOffset:vo,Value:value,SanityOffset:so,SanityValue:sanity,EndOffset:p})}if(ids.includes(id))records.push({ObjectId:id,BaseId:base,Table:table,RecordIndex:ri,StartOffset:start,EndOffset:p,Reserved0:rc,Reserved1:reserved,ModificationCountOffset:mcOffset,ModificationCount:mc,SemanticKind:kinds[ids.indexOf(id)],Fields:fields})}tables.push({Name:table,CountOffset:co,RecordCount:count,RecordsStartOffset:rs,EndOffset:p})}
assert(p===b.length&&records.length===7,'EOF / rewards');records.sort((a,b)=>ids.indexOf(a.ObjectId)-ids.indexOf(b.ObjectId));
const parsed=JSON.parse(fs.readFileSync(path.join(docs,'object-diff/2.320.w3u.json')));assert(parsed.objectCount===total&&parsed.parsedEndOffset===p,'independent layout');for(const r of records){const o=parsed.tables.flatMap(t=>t.objects).find(o=>o.id===r.ObjectId);assert(o.offset===r.StartOffset&&o.endOffset===r.EndOffset&&o.fieldCount===r.ModificationCount,'independent record');for(const f of r.Fields){const q=o.fields[f.ModificationIndex];assert(q.offset===f.StartOffset&&q.valueOffset===f.ValueOffset&&q.endOffset===f.EndOffset&&String(q.value)===f.Value,'independent field')}}
const w=bytes['war3map.wts'],lines=[];for(let pos=0;pos<w.length;){const start=pos,n=w.indexOf(10,pos);pos=n<0?w.length:n+1;let end=n<0?w.length:n;if(w[end-1]===13)end--;lines.push({start,end,next:pos,text:w.toString('latin1',start,end)})}const entries=new Map();for(let n=0;n<lines.length;n++){const match=/^(?:ï»¿)?STRING\s+(\d+)\s*$/.exec(lines[n].text);if(!match)continue;const id=Number(match[1]),start=lines[n].start;assert(!entries.has(id),'duplicate WTS');while(++n<lines.length&&lines[n].text!=='{'){}assert(n<lines.length,'open WTS');const ts=lines[n].next;while(++n<lines.length&&lines[n].text!=='}'){}assert(n<lines.length,'close WTS');let te=lines[n].start;if(w[te-1]===10)te--;if(w[te-1]===13)te--;const end=lines[n].next;entries.set(id,{RecordId:id,RecordStartOffset:start,RecordEndOffset:end,TextStartOffset:ts,TextEndOffset:te,ResolvedText:w.toString('utf8',ts,te),RecordSha256:hash(w.subarray(start,end))})}
const wr=[];for(const r of records)for(const f of r.Fields.filter(f=>['unam','utip'].includes(f.FieldId))){const m=/^TRIGSTR_(\d+)$/.exec(f.Value);assert(m,'WTS reference');const e=entries.get(Number(m[1]));assert(e&&Buffer.from(e.ResolvedText).equals(w.subarray(e.TextStartOffset,e.TextEndOffset)),'target WTS UTF8');wr.push({ObjectId:r.ObjectId,FieldId:f.FieldId,...e})}
const jl=bytes['war3map.j'].toString('utf8').split(/\r?\n/),order=['n000','n002','n003','n004','n005','n006','n007','n008','n00A','n001','n00C','n00D','n00B','n009'],hex=id=>'$'+Buffer.from(id).toString('hex');const pin=(s,e,purpose)=>({Artifact:'war3map.j',StartLine:s+1,EndLine:e+1,Purpose:purpose}),jp=[];
for(const id of order){const hits=jl.map((s,n)=>s.includes('CreateUnit(Player(5),'+hex(id)+',')?n:-1).filter(n=>n>=0);assert(hits.length===1,'unique objective '+id);jp.push(pin(hits[0],hits[0],'owner-5 objective '+id+' creation'))}
const starts=jl.map((s,n)=>/^set \w+\[0\]=/.test(s)&&s.endsWith('='+hex('n000'))?n:-1).filter(n=>n>=0);assert(starts.length===1,'table');const st=starts[0],name=/^set (\w+)/.exec(jl[st])[1];order.forEach((id,n)=>assert(jl[st+n]==='set '+name+'['+n+']='+hex(id),'ordered table'));jp.push(pin(st,st+13,'ordered story objective table'));
for(const id of ['e0IX','e018','e017']){const hits=jl.map((s,n)=>s.startsWith('call ')&&s.includes(','+hex(id)+',')&&s.endsWith(',bj_UNIT_FACING)')?n:-1).filter(n=>n>=0);const ranges=hits.map(h=>{let s=h,e=h;while(s>=0&&!jl[s].startsWith('function '))s--;while(e<jl.length&&jl[e]!=='endfunction')e++;return {s,e}}).filter(x=>x.e-x.s===4&&jl[x.s].includes('takes player ')&&jl[x.s].includes(',integer '));assert(ranges.length===1,'bounded reward factory '+id);jp.push(pin(ranges[0].s,ranges[0].e,'bounded reward unit factory for '+id))}
const result={MapVersion:'2.320',Archive:{FileName:'ORDR_S2_2.320[R].w3x',LengthBytes:JSON.parse(fs.readFileSync(path.join(docs,'mpq-headers.json'))).find(x=>x.version==='2.320').length,Sha256:manifest.currentArchiveSha256.toLowerCase()},Members:members,JassPins:jp,W3uEvidence:{MemberName:'war3map.w3u',ParserLimits:{MaxMemberBytes:536870912,MaxTables:2,MaxRecordsPerTable:100000,MaxModificationsPerRecord:100000,MaxStringBytes:1048576},Layout:{Version:version,HeaderEndOffset:4,Tables:tables,TotalRecordCount:total,TotalModificationCount:mods,ZeroSanityMarkerCount:zero,ConsumedBytes:p,TrailingBytes:0},Records:records},WtsEvidence:{MemberName:'war3map.wts',TargetTextEncoding:'UTF-8',ParsedRecordCount:entries.size,Records:wr}};
const canonical=o=>Array.isArray(o)?'['+o.map(canonical).join(',')+']':o&&typeof o==='object'?'{'+Object.keys(o).sort().map(k=>JSON.stringify(k)+':'+canonical(o[k])).join(',')+'}':JSON.stringify(o);
const out=Buffer.from(JSON.stringify(result,null,2)+'\n');fs.writeFileSync(process.argv[2]||path.join(root,'Data/map-source-metadata-2320.json'),out);console.log(JSON.stringify({dataSha256:hash(out),semanticSha256:hash(canonical(result)),layout:result.W3uEvidence.Layout,jassPins:jp,records:records.map(r=>({id:r.ObjectId,start:r.StartOffset,end:r.EndOffset,modifications:r.ModificationCount})),wtsCount:entries.size},null,2));
