<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseSystemDrawing>true</UseSystemDrawing>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Map2322VisualCapture</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../OrandOverlay.csproj" />
  </ItemGroup>
</Project>
